### ISSUE TITLE
Crash after repeating a game 

### ISSUE THREAD

**Issue by asierigle** [markitus18/Project-II#101]
**Class:** Critical
**Type:** Hang.  
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Win or lose one game recently created.  
2.   Start again and you won't be able to select units.   

**RESULTS:**  
The game stops and eventually crashes on C_String.  

**EXPECTED RESULTS:**  
It should go fine like nothing happens.   

**ADDITIONAL INFO:**  
It happens because it can't find an image texture.

**Comment by DRed96** [comment]
It was related to issue #102
