### ISSUE TITLE
When Kerrigan or the Zerg sample dies, a UI image goes wrong

### ISSUE THREAD

**Issue by Vulpem** [markitus18/Project-II#102]
**Type:** Functionality
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Kill Kerrigan or the Zerg Sample
2.   When Kerrigan explodes or the Sample turns to rubble, look at the output (Log)
3.   A UI image is going crazy! Even after closing the scene. An element isn't being erased properly.

**Comment by DRed96** [comment]
It was the victory/defeat screen. It is solved now
