### ISSUE TITLE
Crash while killing unit

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#104]
**Class:** Critical
**Type:** Crash/Hang
**Frequency:** %   

**STEPS TO REPRODUCE:**  
1.   Skip First cinematic
2.   Spawn an infested terran and a probe
3.   The terran kills the probe

**RESULTS:**  
Game crashes before the terran explodes

**ADDITIONAL INFO:** 
line 1402:Unit.cpp -> Hp Bar is NULL
Debug

**Comment by Vulpem** [comment]
fixed
