### ISSUE TITLE
Game crash quan surts del menu

### ISSUE THREAD

**Issue by asierigle** [markitus18/Project-II#18]
Class: Major
Type: Crash
Frequency: 100%

STEPS TO REPRODUCE:
1. Start a game with the menu activated.
2. Press Quit or Launch Game.
3. Observe that the game crashes.

RESULTS:
You can no longer play the game.

ADDITIONAL INFO:
It's probably the destructor of the Create Input Text.

**Comment by DRed96** [comment]
We should uncomment the UI_InputText destructor
