### ISSUE TITLE
Could not move a unit(templar) when he was about to die.

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#19]
Class: Minor
Type: Gameplay
Frequency: ???%

STEPS TO REPRODUCE:
1. Create lots of units(including the ones that are not in the game) where the debug buildings are.
2. Go to the south east zerg base and .
3. Wait until a unit has low life.
4. Try to move it
5. It dies.

RESULTS:
You can't move the unit, it dies, the dying animation is not displayed and you can no longer select it.

**Comment by asierigle** [comment]
Haurias de dir quin es el nom de la unitat que no es mou... XD

**Comment by Vulpem** [comment]
should be fixed. The problem should be the same that caused the "shadow zerglings". We'll close this if it doesn't reappear.

**Comment by Vulpem** [comment]
It hasn't happened since we fixed the "shadow Zerglings", assuming it's solved. If it reappears, we'll reoppen it.
