### ISSUE TITLE
Invisible shadows that count a unit

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#20]
Class: Minor
Type: Gameplay  
Frequency: ???%   

STEPS TO REPRODUCE:  
1.Go to the hydralisk base and destroy it.

RESULTS:  
Invisible shadows that in the minimap appear as units. 

ADDITIONAL INFO:  

![9k](https://cloud.githubusercontent.com/assets/9281638/14968330/86794e16-10bc-11e6-938d-3b0282c424e7.jpg)

**Comment by Vulpem** [comment]
Noted. Creiem que aixó passa quan es borren les unitats mentre estan esperant un path, ho arreglarem de seguida que puguem.
