### ISSUE TITLE
Boss will walk even while stunned

### ISSUE THREAD

**Issue by Vulpem** [markitus18/Project-II#33]
**Class:** Major
**Type:** Gameplay, Functionality, A.I., Camera

**Frequency:** Almost 100%   

**STEPS TO REPRODUCE:**  
1.   Spawn the boss naturally or by pressing F8
2.   Deplete his shield while she's making any explosion
3.   She'll start walking when she's done with the explosion, ignoring the stun explosion/state

**RESULTS:**  
Boss will walk while it should be stunned. Also, as a result of going out of the "stunned state" incorrectly, it won't regain it shield again.

**EXPECTED RESULTS:**  
Boss should stay still and not move for about 20 seconds after her shield is depleted.

**ADDITIONAL INFO:**

**Comment by GottaCodeHarder** [comment]
Intentare tenerlo para esta noche
