### ISSUE TITLE
When the boss dies it shows a corpse of an ultralisk

### ISSUE THREAD

**Issue by asierigle** [markitus18/Project-II#36]
**Class:** Minor  
**Type:** Graphics.  
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Kill the boss.  
2.   It will show a corpse of a dead ultralisk.   

**RESULTS:**  
The corpse is not the one that should have the boss.   

**EXPECTED RESULTS:**  
See another corpse.

**Comment by GottaCodeHarder** [comment]
We need sprites for it
