### ISSUE TITLE
Game design issues

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#44]
This would be a good place to list all the game design issues that could improve the game!

**Comment by DRed96** [comment]
1. Zerg Bases don't need strategy, kinda boring.  
   1. High templars are OP.
   2. Munchkin
2. Stargate is unnecessary.
3. The boss is the fun part!  

In my opinion the Zerg bases can be destroyed just by throwing lots of units at them they just feel like: Collect resources->Wait until building units->Throw them in the base->Kill the base->Repeat. 

This is related to the second issue, you can do that because High Templars feel pretty strong (maybe other units are but that's the impression I got, maybe because of visuals). What I'm trying to say is that destroying the enemy bases is easy, mindless and takes a lot of time (it's not fun at all >_<).

Another reason this happens it's that the player can arm up and gather too much resources and units, making him almost undefeatable even for the boss. (OP units + Not so aggressive AI + Abundant resources) makes the player invulnerable to the small attacks from the AI and able to kill the boss without much effort.

By the way, I completed the game without creating the Stargate (because I forgot to include the order LOL). This relates to the OP units, I don't know if that's a super important issue but it might be.

Now let's get to the fun part, the boss.

I don't want to sound pessimistic but I think that we've failed at creating an strategy game, because (right now, maybe with some number balancing we can fix this) our game has no strategy at all; in part because of the things I've previously said. But we've succeed at creating a really cool boss. Fighting Kerrigan is fun and it can be even better if we spend time improving it and making it a challenging experience that everyone wants to play (maybe even re-play!).

**Conclusion**
Where am I going with this? The game needs a **lot** of game design  work to do and the amount of days we've proposed to do so, in my opinion, will not be enough. I want the game to look as good as possible, even if I haven't worked on it as much as I should (Sorry v_v) so it would be nice to put a solution to this. I propose two options.

One option is that the whole team makes an extra effort to solve as much bugs, as fast as possible so we can have more time to balance the game and make it fun. The other one is to make the game designer, and maybe other people, start working on balancing the numbers while the rest of the team is focussed on bug-fixing.

**Comment by GottaCodeHarder** [comment]
Okey I'm on it, but it's difficult to create a game balanced for newbs and pro players both at the same time with the match time restriction

**Comment by GottaCodeHarder** [comment]
We need to close several things to re-balance again the stuff.

**Comment by GottaCodeHarder** [comment]
We may open it after the class test.
