### ISSUE TITLE
Some random issue for our lead David that wants to fix Fog of War

### ISSUE THREAD

**Issue by markitus18** [markitus18/Project-II#55]
**Class:** Minor
**Type:** Functionallity
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Move our observer to some place in the map

**RESULTS:**  
The observer is sometimes not drawn, because the FoW is not updated properly and detects it is in a non-visible zone

**EXPECTED RESULTS:**  
FoW should draw a circle in our observer and observer should be visible

**ADDITIONAL INFO:**  
Fack u david, this is boring :/

**Comment by Vulpem** [comment]
Feels good to close this fast
