### ISSUE TITLE
Pylons should display build area when selected

### ISSUE THREAD

**Issue by markitus18** [markitus18/Project-II#61]
**Class:**Minor  
**Type:**Functionality
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Select a pylon

**RESULTS:**  
Doesn't display build area

**EXPECTED RESULTS:**  
All pylons should display build area when a pylon is selected

**Comment by GottaCodeHarder** [comment]
Antes iria el corregir la posicion de las unidades, nadie le da click a los pilones para saber hasta donde llega la energia.
