### ISSUE TITLE
Kerrigan's Zerglings make a huge pathfinding

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#77]
**Class:** Minor 
**Type:**  Frame Rate
**Frequency:** %   

Clarified in video: 
https://drive.google.com/file/d/0BxXvIqO1rsVbRGhjLWc2LXNBTG8/view?usp=sharing

**STEPS TO REPRODUCE:**  
1.   Activate debug pathfinding.
2.  Attack Kerrigan with a bunch of units and wait until she spawns Zerglings.
3.    Move your units Back and forth.

**RESULTS:**  
Zerglings pathfinding is enormous.

**EXPECTED RESULTS:**  
Normal pathfinding.

**ADDITIONAL INFO:**

**Comment by GottaCodeHarder** [comment]
Es podria fer que calcules una unica ruta y que no es renoves cada cop que es fes una explosio

**Comment by Vulpem** [comment]
Will move this issue to a more appropiate form. The bug isn't about kerrigan Zerglings
