### ISSUE TITLE
Vespene Geyser and Assimilator does not have Animation

### ISSUE THREAD

**Issue by GottaCodeHarder** [markitus18/Project-II#79]
**Class:** Minor  
**Type:**Graphics.    

**STEPS TO REPRODUCE:**  
1. Watch the Vespene Geyser  
2. Build an Assimilator  
3. Watch the Assimilator   

**RESULTS:**  
No gas vespene feedback

**EXPECTED RESULTS:**  
Green Gas Animation while on Geyser and Assimilator

**ADDITIONAL INFO:**  
We have sprites

**Comment by Vulpem** [comment]
It will probably stay like this, as much i'd like to, it's not needed.
