### ISSUE TITLE
People doesn't know when they should attack

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#82]
Players have no idea when they have enough troops to destroy a base, maybe putting a little text like. Build X Zealots, Y Dragoons, Z other unit. Like starcraft 2 tutorial.
Also the player doesn't know which units are strong and which ones are weak

**Comment by GottaCodeHarder** [comment]
??? This should be each player's criteria. Also on the intelligence of the player I'd say, if you keep building Zealots even after creating Templar Archives that cost 500 mineral 400 gas that unlocks new units I don't think this is a game's fault.
Maybe we can redo the mini-text of each units.
