### ISSUE TITLE
Players end up having large quantities of gas and lacking of minerals

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#85]
When some time passes (about 10~15 min) players used to have about 1200 of gas and 130 of mineral

**Comment by GottaCodeHarder** [comment]
Depends on the player... but we can increase the time a Probe is inside the Assimilator

**Comment by GottaCodeHarder** [comment]
Ah, and reducing the amount of gas a geyser has from 6000 to 5000

**Comment by markitus18** [comment]
What??

**Comment by GottaCodeHarder** [comment]
Increase the time the Probe spends gathering Gas inside the Assimilator

**Comment by markitus18** [comment]
How much time? I'll tell you the code line and you test it as you want :)

**Comment by GottaCodeHarder** [comment]
Okey I'll do it myself :octocat:
