### ISSUE TITLE
Boss is super hard

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#88]
Gotta balance it

**Comment by Vulpem** [comment]
Em costa acceptar aixó... el Boss no es fácil, per aixó es un boss.
I ara mateix, nosaltres jugant el podem matar abans de que deixi la base Zerg en la que spawneja. Suposo que podem variar els seus estats segons el nombre de bases o la "dificultat" que es seleccioni, pero no crec que puguem fer gaire més. Nerfejar-lo massa fará que sigui fácil, i si es fácil serà aborrit,

**Comment by Vulpem** [comment]
Boss has diferent stats depending on the difficulty now
