### ISSUE TITLE
Units should stop killing each other during the boss cinematic

### ISSUE THREAD

**Issue by Vulpem** [markitus18/Project-II#94]
Major
 Functionality, A.I.
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Make the boss spawn, but wihtout killing all the Zerg Units.
2.   Make sure there are protoss units around.
3.   While the cinematic is running, units will still fight each other and die, with the player having absolutely no control over them.

**RESULTS:**  
While the cinematic is running, units will continue to fight, attack and die, without the player being able to do anything about it.

**EXPECTED RESULTS:**  
The units should stop fighting or, at least, recieve no damage from the fighting while the cinematic is going on.

**ADDITIONAL INFO:**

**Comment by GottaCodeHarder** [comment]
Agreed
