### ISSUE TITLE
Leaving the game with the console open does not close it

### ISSUE THREAD

**Issue by DRed96** [markitus18/Project-II#96]
**Class:** Minor  
**Type:** Functionality 
**Frequency:** 100%   

**STEPS TO REPRODUCE:**  
1.   Open the game, open the console
2.   Close the game with the console opened

**RESULTS:**  
The console is mantained there.

**Comment by GottaCodeHarder** [comment]
Same happens with Debug Mode (F1), when u enter again in the match you see everything in Debug and you can't close it

**Comment by Vulpem** [comment]
it's supposed to be like this. I'll make it prettier, though
